
services:
#  postgres:
#    image: postgres:16
#    container_name: csv_transactions_db
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: Password123!
#      POSTGRES_DB: transactions_db
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", '""', "--appendonly", "no"]

  worker:
    build:
      context: .
      dockerfile: celery_app/celery.Dockerfile
    depends_on:
      - redis
#      - postgres
    environment:
      celery_broker_uri: redis://redis:6379


volumes:
  postgres_data:
