
services:
  postgres:
    image: postgres:16
    container_name: csv_transactions_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: transactions_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
